{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* nvNewsletter - edit receiver *}
<form method="post" action={concat('/nvnewsletter/edit_receiver/', $receiver.id, '/')|ezurl}>

{if $warning|count}
    <div class="message-warning">
    <h2>{'The validation of your entries failed.'|i18n('design/nvnewsletter' )}</h2>
    <ul>
    {foreach $warning as $warningmessage}
        <li>{$warningmessage|wash}</li>
    {/foreach}
    </ul>
    </div>
{/if}

<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h1 class="context-title">{'Edit receiver'|i18n( 'design/nvnewsletter' )}</h1>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content">

<input type="hidden" name="ReceiverID" value ="{$receiver.id}"/>

<div class="context-attributes">

{* Email. *}
<div class="block">
<label for="email">{'Email'|i18n( 'design/nvnewsletter' )}:</label>
<input id="email" class="box" id="receiverEmail" type="text" name="ReceiverEmail" value="{$receiver.email_address|wash}" />
</div>

<div class="block">
{* Groups. *}
<label>{'Receiver group(s)'|i18n( 'design/nvnewsletter' )}:</label>
<table border="0" cellpadding="0" cellspacing="0">
{def $curGroups=$receiver.groups}
{def $selGroup=false()}
{foreach $receiver_group_array as $group}
    {set $selGroup=false()}
    {foreach $curGroups as $curGroup}
        {if $curGroup.id|eq($group.id)}
            {set $selGroup=$curGroup}
        {/if}
    {/foreach}
    <tr>
        <td><label class="checkbox"><input type="checkbox" name="ReceiverGroupIDArray[]" value="{$group.id}" {if $selGroup} checked="checked"{/if} /> {$group.group_name|wash}</label></td>
        <td style="padding-left: 10px;">
            <label class="checkbox"><input type="radio" name="ReceiverGroupFormatArray[{$group.id}]" value="1" {if or(and($selGroup, $selGroup.mail_type|eq(1)), $selGroup|not)} checked="checked"{/if} /> HTML</label>
            <label class="checkbox"><input type="radio" name="ReceiverGroupFormatArray[{$group.id}]" value="0" {if and($selGroup, $selGroup.mail_type|eq(0))} checked="checked"{/if}/> TEXT</label>
        </td>
    </tr>
{/foreach}
{undef $curGroups}
</table>
</div>

{foreach $receiver.fields as $field}
    <div class="block">
        <label for="receiverfield{$field.id}">{$field.field_name}:</label>
        <input id="receiverfield{$field.id}" class="box" type="text" name="ReceiverFields[{$field.id}]" value="{$field.value|wash}" />
    </div>
{/foreach}

</div>

{* DESIGN: Content END *}</div></div></div>

<div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
<div class="block">
{if $status}
<input type="hidden" name="ReceiverStatus" value="new" />
{/if}
<input class="button" type="submit" name="StoreButton" value="{'OK'|i18n( 'design/nvnewsletter' )}" />
<input class="button" type="submit" name="CancelButton" value="{'Cancel'|i18n( 'design/nvnewsletter' )}" />
</div>
{* DESIGN: Control bar END *}</div></div></div></div></div></div>
</div>

</div>
</form>


{literal}
<script language="JavaScript" type="text/javascript">
<!--
    window.onload=function() {
        document.getElementById('receiverEmail').select();
        document.getElementById('receiverEmail').focus();
    }
-->
</script>
{/literal}
