{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* nvNewsletter - edit receiver group *}
<form method="post" action={concat('/nvnewsletter/edit_receiver_group/', $group.id, '/')|ezurl}>

{if $warning|count}
    <div class="message-warning">
    <h2>{'The validation of your entries failed.'|i18n('design/nvnewsletter' )}</h2>
    <ul>
    {foreach $warning as $warningmessage}
        <li>{$warningmessage|wash}</li>
    {/foreach}
    </ul>
    </div>
{/if}


<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h1 class="context-title">{'Edit receiver group'|i18n( 'design/nvnewsletter' )}</h1>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content">

<input type="hidden" name="ReceiverGroupID" value ="{$group.id}"/>

<div class="context-attributes">

{* Name. *}
<div class="block">
<label>{'Name'|i18n( 'design/nvnewsletter' )}:</label>
<input class="box" id="receiverGroupName" type="text" name="ReceiverGroupName" value="{$group.group_name|wash}" />
</div>

{* Description. *}
<div class="block">
<label>{'Description'|i18n( 'design/nvnewsletter' )}:</label>
<textarea class="box" id="receiverGroupDescription" name="ReceiverGroupDescription" rows="10">{$group.group_description|wash}</textarea>
</div>

</div>

{* DESIGN: Content END *}</div></div></div>

<div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
<div class="block">
<input class="button" type="submit" name="StoreButton" value="{'OK'|i18n( 'design/nvnewsletter' )}" />
<input class="button" type="submit" name="CancelButton" value="{'Cancel'|i18n( 'design/nvnewsletter' )}" />
</div>
{* DESIGN: Control bar END *}</div></div></div></div></div></div>
</div>

</div>
</form>


{literal}
<script language="JavaScript" type="text/javascript">
<!--
    window.onload=function() {
        document.getElementById('receiverGroupName').select();
        document.getElementById('receiverGroupName').focus();
    }
-->
</script>
{/literal}
