{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* nvNewsletter - receiver import *}
{def $base_uri=concat('/nvnewsletter/import_receivers/', $group.id)}

{if is_set($warning)}
    <div class="message-warning">
        <h2>{$warning|wash}</h2>
    </div>
{/if}

{if is_set( $imported )}
    <div class="{if or( $import_result.failed|gt(0), $import_result.success|eq(0) )}message-warning{else}message-feedback{/if}">
        <h2>{'CSV imported with following results'|i18n( 'design/nvnewsletter' )}</h2>
        <h4>{'Total'|i18n( 'design/nvnewsletter' )}: {$import_result.total}</h4>
        <ul>
            <li>{'Receivers imported'|i18n( 'design/nvnewsletter' )}: {$import_result.success}</li>
            <li>{'Receivers already in system'|i18n( 'design/nvnewsletter' )}: {$import_result.exists}*</li>
            <li>{'Receivers failed'|i18n( 'design/nvnewsletter' )}: {$import_result.failed}*</li>
            {if $import_result.failed_array}<li>{'Failed emails'|i18n('design/nvnewsletter')}:
            {def $failed_round = 1}
            {foreach $import_result.failed_array as $failed}
                {$failed|wash}{if $failed_round|lt( $import_result.failed )}, {/if}
                {set $failed_round = $failed_round|inc()}
            {/foreach}
            </li>{/if}
        </ul>
        <p><a href={concat( 'nvnewsletter/view_receiver_group/', $group.id )|ezurl}>{'Go to group %group_name'|i18n('design/nvnewsletter',, hash( '%group_name', $group.group_name ) )}</a></p>
        <p style="font-size:85%">
        * {'Receivers already in system tells that receiver with same email address exists. Subscription status doesn\'t change, but details are updated.'|i18n('design/nvnewsletter')}<br />
        * {'Receivers failed most likely because of unvalid email address.'|i18n('design/nvnewsletter')}
        </p>
    </div>
{/if}

<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h2 class="context-title">{'Import receivers to group <%group_name>'|i18n( 'design/nvnewsletter',, hash( '%group_name', $group.group_name ) )|wash}</h2>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content">

<form enctype="multipart/form-data" name="subscription_import" method="post" action={$base_uri|ezurl}>

<div class="context-attributes">
    {* Name. *}
    <div class="block">
        <label>{"Name"|i18n( 'design/nvnewsletter' )}:</label> {$group.group_name|wash}
    </div>

    <div class="block">
        <label>{"Upload file"|i18n( 'design/nvnewsletter' )}:</label>
        <input type="hidden" name="MAX_FILE_SIZE" value="0" />
        <input name="UploadCSVFile" type="file" /><input type="submit" value="{'Upload file'|i18n( 'design/nvnewsletter' )}" />
        <div class="break"></div>
        <label><input type="checkbox" name="FirstRowLabel"{if $first_row_label} checked="checked"{/if}>{'First row is label'|i18n( 'design/nvnewsletter' )}</label>
    </div>

    {* Output format. *}
    <div class="block">
        <label>{"Output format"|i18n( 'design/nvnewsletter' )}:</label>
        <select name="OutputFormat" title="{'OutputFormat'|i18n( 'design/nvnewsletter' )}">
            <option value="html" {if $output_set|eq('html')}selected="selected"{/if}>HTML</option>
            <option value="text" {if $output_set|eq('text')}selected="selected"{/if}>Text</option>
        </select>
    </div>

    <div class="block">
        <label>{'CSV field delimiter'|i18n( 'design/nvnewsletter' )}: <input style="text-align:center" type="text" size="1" maxlength="1" name="CSVDelimiter" value="{$CSVDelimiter}"></label>
    </div>
</div>

{* DESIGN: Content END *}</div></div></div>

    {* Buttons. *}
    <div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">


{* DESIGN: Control bar END *}</div></div></div></div></div></div>
    </div>

<div class="context-block">

{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h2 class="context-title">{'Import receivers from CSV'|i18n( 'design/nvnewsletter' )}</h2>
{* DESIGN: Subline *}<div class="header-subline"></div>
{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN:  START *}<div class="box-ml"><div class="box-mr"><div class="box-content">
<div class="context-attributes">

{* Subscription import table. *}
<table class="list" cellspacing="0">
<tr>
    <th class="tight">{'RowNum'|i18n('design/nvnewsletter')}</th>
    {def $maxCount=0}
    {foreach $data as $label => $dataSet}
        {set $maxCount=count( $dataSet )}
        <th>{$label|wash}</th>
    {/foreach}
</tr>
<tr>
   <td>&nbsp;</td>
    {foreach $data as $label => $dataSet}
        <td><select name="LabelMap_{$label|wash}">
            <option value="0">{'None'|i18n( 'design/nvnewsletter' )}</option>
            <option value="email">{'Email'|i18n( 'design/nvnewsletter' )}</option>
            {foreach $receiver_field_array as $field
                     sequence array( bglight, bgdark ) as $seq}
                <option value="field{$field.id}">{$field.field_name|wash()}</option>
            {/foreach}
            </select>
        </td>
    {/foreach}
</tr>

{if $maxCount|ge(1)}

{def $dataSets = 0}

{for 0 to $show_count as $count sequence array( bglight, bgdark ) as $seq}
    <tr class="{$seq}">
        <td class="number" align="right">{$count}</td>
    {set $dataSets = 0}
    {foreach $data as $label => $dataSet}
        <td>{$dataSet[$count]|wash}</td>
        {set $dataSets = $dataSets|inc()}
    {/foreach}
    </tr>
{/for}
    <tr>
        <td class="rowsTotal" colspan="{$dataSets|sum(1)}"><strong>{$line_count} {'rows total.'|i18n('design/nvnewsletter')}</strong></td>
    </tr>
{/if}
</table>

{* DESIGN: Table END *}</div></div></div>

    <div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
        <div class="block">
            <input class="button" type="submit" name="CancelButton" value="{'Cancel'|i18n( 'design/nvnewsletter' )}" title="{'Cancel subscription import.'|i18n( 'design/nvnewsletter' )}" />
            <input class="button" type="submit" name="ImportButton" value="{'Import receivers'|i18n( 'design/nvnewsletter' )}" title="{'Import selected'|i18n( 'design/nvnewsletter' )}" />
        </div>
{* DESIGN: Control bar END *}</div></div></div></div></div></div>
    </div>
</form>
</div>