{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* nvNewsletter - receiver field list *}
{def $receiverFieldCount=fetch('nvnewsletter', 'receiver_field_count')}
<form name="receiver_fields" method="post" action={'/nvnewsletter/list_receiver_fields/'|ezurl}>

<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h1 class="context-title">{'Newsletter receiver fields'|i18n( 'design/nvnewsletter' )} [{$receiverFieldCount}]</h1>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content overflow">

{* Items per page selector. *}
<div class="context-toolbar">
<div class="block">
<div class="left">

</div>
<div class="break"></div>
</div>
</div>

{* Newsletter receiver field table. *}
<table class="list" cellspacing="0">
<tr>
    <th class="tight"><img src={'toggle-button-16x16.gif'|ezimage} alt="{'Invert selection'|i18n('design/nvnewsletter')}" title="{'Invert selection.'|i18n('design/nvnewsletter')}" onclick="ezjs_toggleCheckboxes( document.receiver_fields, 'ReceiverFieldIDArray[]' ); return false;" /></th>
    <th>{'Name'|i18n( 'design/nvnewsletter' )}</th>
    <th>{'Type'|i18n( 'design/nvnewsletter' )}</th>
    <th class="tight">{'Required'|i18n( 'design/nvnewsletter' )}</th>
    <th class="tight">{'ID'|i18n( 'design/nvnewsletter' )}</th>
    <th class="tight">&nbsp;</th>
</tr>
{if $receiverFieldCount|lt(1)}
<tr><td>&nbsp;</td><td colspan="4">{'No receiver fields'|i18n( 'design/nvnewsletter' )}</td><td>&nbsp;</td></tr>
{else}
{foreach $receiver_field_array as $field
         sequence array( bglight, bgdark ) as $seq}
<tr class="{$seq}">
    <td><input type="checkbox" name="ReceiverFieldIDArray[]" value="{$field.id}" title="{'Select receiver field for removal.'|i18n( 'design/nvnewsletter' )}" /></td>
    <td>{'newsletter'|icon( 'small', 'Newsletter'|i18n( 'design/nvnewsletter' ) )}&nbsp;<a href={concat( '/nvnewsletter/view_receiver_field/', $field.id, '/' )|ezurl}>{$field.field_name|wash}</a></td>
    <td>{$field.field_type}</td>
    <td class="number" align="right">{if $field.required}X{else}&nbsp;{/if}</td>
    <td class="number" align="right">{$field.id}</td>
    <td><a href={concat( '/nvnewsletter/edit_receiver_field/', $field.id, '/' )|ezurl}><img src={'edit.gif'|ezimage} alt="{'Edit'|i18n( 'design/nvnewsletter' )}" title="{'Edit the <%field_name> receiver field.'|i18n( 'design/nvnewsletter',, hash( '%field_name', $field.field_name ) )|wash}" /></a></td>
    </tr>
{/foreach}
{/if}
</table>

{* Navigator. *}
<div class="context-toolbar">
{*
{include name=navigator
         uri='design:navigator/google.tpl'
         page_uri='/nvnewsletter/list_receiver_fields'
         item_count=$receiverFieldCount
         view_parameters=$view_parameters
         item_limit=$limit}
         *}
</div>

{* DESIGN: Content END *}</div></div></div>

{* Buttons. *}
<div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
<div class="block">
<input class="button" type="submit" name="RemoveReceiverFieldButton" value="{'Remove selected'|i18n( 'design/nvnewsletter' )}" title="{'Remove selected receiver fields.'|i18n( 'design/nvnewsletter' )}" />
<input class="button" type="submit" name="CreateReceiverFieldButton" value="{'New field'|i18n( 'design/nvnewsletter' )}" title="{'Create a new receiver field.'|i18n( 'design/nvnewsletter' )}" />
</div>
{* DESIGN: Control bar END *}</div></div></div></div></div></div>
</div>
</div>
</form>
