{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* nvNewsletter - receiver group list *}
{def $groupCount=fetch('nvnewsletter', 'receiver_group_count')
     $page_limit = $limit}
<form name="receiverGroups" method="post" action={'/nvnewsletter/list_receiver_groups/'|ezurl}>

<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h1 class="context-title">{'Newsletter receiver groups'|i18n( 'design/nvnewsletter' )} [{$groupCount}]</h1>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content overflow">

{* Items per page selector. *}
<div class="context-toolbar">
<div class="button-left">
    <p class="table-preferences">
        {switch match=$page_limit}
        {case match=25}
        <a href={'/user/preferences/set/admin_list_limit/1'|ezurl} title="{'Show 10 items per page.'|i18n( 'design/admin/node/view/full' )}">10</a>
        <span class="current">25</span>
        <a href={'/user/preferences/set/admin_list_limit/3'|ezurl} title="{'Show 50 items per page.'|i18n( 'design/admin/node/view/full' )}">50</a>
        {/case}

        {case match=50}
        <a href={'/user/preferences/set/admin_list_limit/1'|ezurl} title="{'Show 10 items per page.'|i18n( 'design/admin/node/view/full' )}">10</a>
        <a href={'/user/preferences/set/admin_list_limit/2'|ezurl} title="{'Show 25 items per page.'|i18n( 'design/admin/node/view/full' )}">25</a>
        <span class="current">50</span>
        {/case}

        {case}
        <span class="current">10</span>
        <a href={'/user/preferences/set/admin_list_limit/2'|ezurl} title="{'Show 25 items per page.'|i18n( 'design/admin/node/view/full' )}">25</a>
        <a href={'/user/preferences/set/admin_list_limit/3'|ezurl} title="{'Show 50 items per page.'|i18n( 'design/admin/node/view/full' )}">50</a>
        {/case}
        {/switch}
    </p>
</div>
<div class="float-break"></div>
</div>

{* Newsletter receiver group table. *}
<table class="list" cellspacing="0">
<tr>
    <th class="tight"><img src={'toggle-button-16x16.gif'|ezimage} alt="{'Invert selection'|i18n('design/nvnewsletter')}" title="{'Invert selection.'|i18n('design/nvnewsletter')}" onclick="ezjs_toggleCheckboxes( document.receiverGroups, 'ReceiverGroupIDArray[]' ); return false;" /></th>
    <th>{'Name'|i18n( 'design/nvnewsletter' )}</th>
    <th>{'Description'|i18n( 'design/nvnewsletter' )}</th>
    <th class="tight">{'Subscribed'|i18n( 'design/nvnewsletter' )}</th>
    <th class="tight">{'Unsubscribed'|i18n( 'design/nvnewsletter' )}</th>
    <th class="tight">{'ID'|i18n( 'design/nvnewsletter' )}</th>
    <th class="tight">&nbsp;</th>
</tr>
{if $groupCount|lt(1)}
<tr><td>&nbsp;</td><td colspan="3">{'No receiver groups'|i18n( 'design/nvnewsletter' )}</td><td>&nbsp;</td></tr>
{else}
{def $members_count = 0
     $members_unsubscribed_count = 0}
{foreach $receiver_group_array as $group sequence array( bglight, bgdark ) as $seq}
    {set $members_count = $group.members_count
         $members_unsubscribed_count = $group.members_unsubscribed_count}
<tr class="{$seq}">
    <td><input type="checkbox" name="ReceiverGroupIDArray[]" value="{$group.id}" title="{'Select receiver group for removal.'|i18n( 'design/nvnewsletter' )}" /></td>
    <td>{'newsletter'|icon( 'small', 'Newsletter'|i18n( 'design/nvnewsletter' ) )}&nbsp;<a href={concat( '/nvnewsletter/view_receiver_group/', $group.id, '/' )|ezurl}>{$group.group_name|wash}</a></td>
    <td>{$group.group_description|wash}</td>
    <td class="number" align="right"><strong>{$group.members_count}</strong> [{if $members_count|gt(0)}<a href={concat( '/nvnewsletter/export_receivers_group/', $group.id )|ezurl}>CSV</a>{else}CSV{/if}]</td>
    <td class="number" align="right"><strong>{$group.members_unsubscribed_count}</strong> [{if $members_unsubscribed_count|gt(0)}<a href={concat( '/nvnewsletter/export_receivers_group/', $group.id, '/0' )|ezurl}>CSV</a>{else}CSV{/if}]</td>
    <td class="number" align="right">{$group.id}</td>
    <td><a href={concat( '/nvnewsletter/edit_receiver_group/', $group.id, '/' )|ezurl}><img src={'edit.gif'|ezimage} alt="{'Edit'|i18n( 'design/nvnewsletter' )}" title="{'Edit the <%group_name> receiver group.'|i18n( 'design/nvnewsletter',, hash( '%group_name', $group.group_name ) )|wash}" /></a></td>
</tr>
{/foreach}
{/if}
</table>

{* Navigator. *}
<div class="context-toolbar">
{include name=navigator
         uri='design:navigator/google.tpl'
         page_uri='/nvnewsletter/list_receiver_groups'
         item_count=$groupCount
         view_parameters=$view_parameters
         item_limit=$page_limit}
</div>

{* DESIGN: Content END *}</div></div></div>

{* Buttons. *}
<div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
<div class="block">
<input class="button" type="submit" name="RemoveReceiverGroupButton" value="{'Remove selected'|i18n( 'design/nvnewsletter' )}" title="{'Remove selected receiver groups.'|i18n( 'design/nvnewsletter' )}" />
<input class="button" type="submit" name="CreateReceiverGroupButton" value="{'New group'|i18n( 'design/nvnewsletter' )}" title="{'Create a new receiver group.'|i18n( 'design/nvnewsletter' )}" />
</div>
{* DESIGN: Control bar END *}</div></div></div></div></div></div>
</div>
</div>
</form>
