{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* nvNewsletter - sent newsletter list *}

{def $newsletterCount=fetch('nvnewsletter', 'sent_newsletter_count')
     $senderFieldID=ezini('ContentClassSettings', 'SenderFieldIdentifier', 'nvnewsletter.ini')
     $groupFieldID=ezini('ContentClassSettings', 'GroupsFieldIdentifier', 'nvnewsletter.ini')
     $page_limit = $limit
     $groupData = ''
     $senderData = ''}
<form name="newsletters" method="post" action={'/nvnewsletter/list_sent/'|ezurl}>
<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h1 class="context-title">{'Sent newsletters'|i18n( 'design/nvnewsletter' )}</h1>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content overflow">

{* Items per page selector. *}
<div class="context-toolbar">
<div class="button-left">
    <p class="table-preferences">
        {switch match=$page_limit}
        {case match=25}
        <a href={'/user/preferences/set/admin_list_limit/1'|ezurl} title="{'Show 10 items per page.'|i18n( 'design/admin/node/view/full' )}">10</a>
        <span class="current">25</span>
        <a href={'/user/preferences/set/admin_list_limit/3'|ezurl} title="{'Show 50 items per page.'|i18n( 'design/admin/node/view/full' )}">50</a>
        {/case}

        {case match=50}
        <a href={'/user/preferences/set/admin_list_limit/1'|ezurl} title="{'Show 10 items per page.'|i18n( 'design/admin/node/view/full' )}">10</a>
        <a href={'/user/preferences/set/admin_list_limit/2'|ezurl} title="{'Show 25 items per page.'|i18n( 'design/admin/node/view/full' )}">25</a>
        <span class="current">50</span>
        {/case}

        {case}
        <span class="current">10</span>
        <a href={'/user/preferences/set/admin_list_limit/2'|ezurl} title="{'Show 25 items per page.'|i18n( 'design/admin/node/view/full' )}">25</a>
        <a href={'/user/preferences/set/admin_list_limit/3'|ezurl} title="{'Show 50 items per page.'|i18n( 'design/admin/node/view/full' )}">50</a>
        {/case}
        {/switch}
    </p>
</div>
<div class="float-break"></div>
</div>

{* Sent newsletters table. *}
<table class="list" cellspacing="0">
<tr>
    <th class="tight"><img src={'toggle-button-16x16.gif'|ezimage} alt="{'Invert selection'|i18n('design/nvnewsletter')}" title="{'Invert selection.'|i18n('design/nvnewsletter')}" onclick="ezjs_toggleCheckboxes( document.newsletters, 'NewsletterIDArray[]' ); return false;" /></th>
    <th class="tight">{'ID'|i18n( 'design/nvnewsletter' )}</th>
    <th>{'Name'|i18n( 'design/nvnewsletter' )}</th>
    <th>{'Sender'|i18n( 'design/nvnewsletter' )}</th>
    <th>{'Receiver groups'|i18n( 'design/nvnewsletter' )}</th>
    <th>{'Sent time'|i18n( 'design/nvnewsletter' )}</th>
    <th>{'End time'|i18n( 'design/nvnewsletter' )}</th>
    <th class="tight">{'# queued'|i18n( 'design/nvnewsletter' )}</th>
    <th class="tight">{'# sent'|i18n( 'design/nvnewsletter' )}</th>
    <th class="tight"></th>
</tr>
{if $newsletterCount|lt(1)}
<tr><td>&nbsp;</td><td colspan="6">{'No sent newsletters'|i18n( 'design/nvnewsletter' )}</td><td>&nbsp;</td></tr>
{else}
{foreach $newsletter_array as $newsletter
         sequence array( bglight, bgdark ) as $seq}
<tr class="{$seq}">
    <td><input type="checkbox" name="NewsletterIDArray[]" value="{$newsletter.id}" title="{'Select newsletter for removal.'|i18n( 'design/nvnewsletter' )}" /></td>
    <td class="number" align="right">{$newsletter.id}</td>
    <td>{'newsletter'|icon( 'small', 'Newsletter'|i18n( 'design/nvnewsletter' ) )}&nbsp;<a href={concat( '/nvnewsletter/view_newsletter/', $newsletter.id, '/' )|ezurl}>{$newsletter.contentobject.name|wash}</a></td>
    {set $senderData=$newsletter.contentobject.data_map[$senderFieldID]}
    <td><a href={concat( '/nvnewsletter/view_sender/', $senderData.content.selected, '/' )|ezurl}>{$senderData.content.options[$senderData.content.selected]}</a></td>
    <td>
        {set $groupData=$newsletter.contentobject.data_map[$groupFieldID]}
        {foreach $groupData.content.options as $key => $option}
            {if eq($groupData.content.selected.$key,'1')}
                <a href={concat( '/nvnewsletter/view_receiver_group/', $key, '/' )|ezurl}>{$option}</a><br />
            {/if}
        {/foreach}
    </td>
    <td>{$newsletter.send_time|makeunixtime()|l10n('shortdatetime')}</td>
    <td>{$newsletter.send_end_time|makeunixtime()|l10n('shortdatetime')}</td>
    <td class="number" align="right">{$newsletter.total_mail_count}</td>
    <td class="number" align="right">{$newsletter.sent_mail_count}</td>
    <td>
        <a href={concat("/nvnewsletter/copy_newsletter/", $newsletter.contentobject.id)|ezurl}><img title="{'Copy newsletter'|i18n( 'design/nvnewsletter' )}" alt="{'Copy'|i18n( 'design/nvnewsletter' )}" src={"copy.gif"|ezimage} /></a>
    </td>
    </tr>
{/foreach}
{/if}
</table>

{* Navigator. *}
<div class="context-toolbar">
{include name=navigator
         uri='design:navigator/google.tpl'
         page_uri='/nvnewsletter/list_sent'
         item_count=$newsletterCount
         view_parameters=$view_parameters
         item_limit=$page_limit}
</div>

{* DESIGN: Content END *}</div></div></div>

{* Buttons. *}
<div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
<div class="block">
<input type="hidden" name="RedirectURIAfterRemove" value={"/nvnewsletter/list_sent"|ezurl} />
<input class="button" type="submit" name="RemoveNewsletterButton" value="{'Remove selected'|i18n( 'design/nvnewsletter' )}" title="{'Remove selected newsletters.'|i18n( 'design/nvnewsletter' )}" />
</div>
{* DESIGN: Control bar END *}</div></div></div></div></div></div>
</div>
</div>
</form>