{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* nvNewsletter - queue draft *}
{def $currentdate=currentdate()}
<form method="post" action={concat('/nvnewsletter/queue_draft/', $newsletter.id, '/')|ezurl}>

{if $warning|count}
    <div class="message-warning">
    <h2>{'The validation of your entries failed.'|i18n('design/nvnewsletter' )}</h2>
    <ul>
    {foreach $warning as $warningmessage}
        <li>{$warningmessage|wash}</li>
    {/foreach}
    </ul>
    </div>
{/if}

<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h1 class="context-title">{'Queue draft'|i18n( 'design/nvnewsletter' )}</h1>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content">

<input type="hidden" name="ReceiverID" value ="{$receiver.id}"/>

<div class="context-attributes">

{* Send time. *}
<div class="block">

<div class="date">
<div class="element">
<label>{'Year'|i18n( 'design/standard/content/datatype' )}:</label>
<input type="text" name="QueueYear" size="5" value="{$currentdate|datetime('custom', '%Y')}" />
</div>

<div class="element">
<label>{'Month'|i18n( 'design/standard/content/datatype' )}:</label>
<input type="text" name="QueueMonth" size="3" value="{$currentdate|datetime('custom', '%m')}" />
</div>

<div class="element">
<label>{'Day'|i18n( 'design/standard/content/datatype' )}:</label>
<input type="text" name="QueueDay" size="3" value="{$currentdate|datetime('custom', '%d')}" />
&nbsp;
&nbsp;
&nbsp;
&nbsp;
</div>
</div>

{def $curHour=$currentdate|datetime('custom', '%H')}
{def $curMinute=$currentdate|datetime('custom', '%i')}
{if and($curMinute|gt(45), $curMinute|le(59))}
    {set $curHour=$curHour|inc}
{/if}

<div class="time">
<div class="element">
<label>{'Hour'|i18n( 'design/standard/content/datatype' )}:</label>
<select name="QueueHour">
{for 0 to 23 as $hour}
    {if $hour|lt(10)}
        {set $hour=concat('0', $hour)}
    {/if}
    <option value="{$hour}" {if $hour|eq($curHour)}selected="selected"{/if}>{$hour}</option>
{/for}
</select>
</div>

<div class="element">
<label>{'Minute'|i18n( 'design/standard/content/datatype' )}:</label>
<select name="QueueMinute">
    <option value="00" {if and($curMinute|gt(45), $curMinute|le(59))}selected="selected"{/if}>00</option>
    <option value="15" {if and($curMinute|ge(0), $curMinute|lt(15))}selected="selected"{/if}>15</option>
    <option value="30" {if and($curMinute|ge(15), $curMinute|lt(30))}selected="selected"{/if}>30</option>
    <option value="45" {if and($curMinute|ge(30), $curMinute|lt(45))}selected="selected"{/if}>45</option>
</select>
</div>

</div>

<div class="break"></div>

</div>

</div>

{* DESIGN: Content END *}</div></div></div>

<div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
<div class="block">
<input class="button" type="submit" name="QueueButton" value="{'OK'|i18n( 'design/nvnewsletter' )}" />
<input class="button" type="submit" name="CancelButton" value="{'Cancel'|i18n( 'design/nvnewsletter' )}" />
</div>
{* DESIGN: Control bar END *}</div></div></div></div></div></div>
</div>

</div>
</form>
