{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* nvNewsletter - create newsletter *}
<form method="post" action={concat('/nvnewsletter/create_newsletter')|ezurl}>
<input type="hidden" name="RedirectURIAfterPublish" value={concat('/nvnewsletter/list_draft')} />
<input type="hidden" name="RedirectIfDiscarded" value={concat('/nvnewsletter/create_newsletter')} />

<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h1 class="context-title">{'Create newsletter'|i18n( 'design/nvnewsletter' )}</h1>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content">

<div class="context-attributes">

<div class="block">
{* Templates. *}
<label for="selectTemplate">{'Select template'|i18n( 'design/nvnewsletter' )}:</label>
<select id="selectTemplate" name="TemplateID">
{foreach $templates as $template}
    <option value="{$template.id}">{$template.name|wash}</option>
{/foreach}
</select>
</div>

</div>

{* DESIGN: Content END *}</div></div></div>

<div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
<div class="block">
<input class="button" type="submit" name="CreateButton" value="{'Create'|i18n( 'design/nvnewsletter' )}" />
</div>
{* DESIGN: Control bar END *}</div></div></div></div></div></div>
</div>

</div>
</form>
