{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* nvNewsletter - receiver view *}

{def $base_uri=concat('/nvnewsletter/view_receiver/', $receiver.id)}

<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h1 class="context-title">{'Receiver <%receiver_email>'|i18n('design/nvnewsletter',, hash('%receiver_email', $receiver.email_address ) )|wash}</h1>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content">

<div class="context-attributes">

    <div class="block float-break">

    {* E-mail *}
    <div class="block float-break">
        <label>{"Email"|i18n('design/nvnewsletter')}:</label> {$receiver.email_address|wash}
    </div>
    <br />

    {foreach $receiver.fields as $field}
        <div class="block float-break">
            <label>{$field.field_name}:</label> {$field.value|wash}
        </div>
        <br />
    {/foreach}
    
    {def $ezuser = $receiver.ezuser}
    {if $ezuser}
    <div class="block float-break">
       <label>{'eZ User'|i18n('design/nvnewsletter')}:</label>
       <a href={$ezuser.contentobject.main_node.url_alias|ezurl}>{$ezuser.contentobject.name}</a>
    </div>
    {/if}

    <div class="break"></div>

</div>

{* DESIGN: Content END *}</div></div></div>
    {* Buttons. *}
    <div class="controlbar" >
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
        {* Edit *}
        <div class="left">
        <form name="edit_receiver" method="post" action={concat('/nvnewsletter/edit_receiver/', $receiver.id)|ezurl} style="display:inline">
        <input class="button" type="submit" value="{'Edit'|i18n('design/nvnewsletter')}" title="{'Edit this receiver.'|i18n('design/nvnewsletter')}" />
        </form>
        
        <form name="unsubscribe_receiver" method="post" action={concat('/nvnewsletter/view_receiver/', $receiver.id)|ezurl} style="display:inline">
        <input class="button" type="submit" name="UnsubscribeReceiver" value="{'Unsubscribe'|i18n('design/nvnewsletter')}" title="{'Unsubscribe this receiver.'|i18n('design/nvnewsletter')}" />
        </form>
        </div>
    </div>


{* DESIGN: Control bar END *}</div></div></div></div></div></div>
</div>
</div>

<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h2 class="context-title">{'Member of groups'|i18n( 'design/nvnewsletter' )}</h2>

{* DESIGN: Mainline *}<div class="header-subline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content">

{* Group member table. *}
<table class="list" cellspacing="0">
<tr>
    <th class="tight">{'ID'|i18n('design/nvnewsletter')}</th>
    <th>{'Name'|i18n('design/nvnewsletter')}</th>
    <th>{'Description'|i18n( 'design/nvnewsletter' )}</th>
    <th>{'Subscribe date'|i18n( 'design/nvnewsletter' )}</th>
    <th>{'Subscribe status'|i18n( 'design/nvnewsletter' )}</th>
</tr>
{foreach $receiver.groups as $group
         sequence array( bglight, bgdark ) as $seq}
<tr class="{$seq}">
    <td class="number">{$group.id}</td>
    <td><a href={concat( '/nvnewsletter/view_receiver_group/', $group.id, '/' )|ezurl}>{$group.group_name|wash}</a></td>
    <td>{$group.group_description|wash}</td>
    <td>{$group.pub_date|makeunixtime()|l10n('shortdatetime')}</td>
    <td>
    {switch match=$group.status}
        {case match=1} 
        {'pending'|i18n( 'design/nvnewsletter' )}
        {/case}
        {case match=2} 
        {'confirmed'|i18n( 'design/nvnewsletter' )}
        {/case}
        {case match=3} 
        {'approved'|i18n( 'design/nvnewsletter' )}
        {/case}
        {case}
        {/case}
    {/switch}
    </td>
</tr>
{/foreach}
</table>

{* DESIGN: Content END *}</div></div></div>

{* Buttons. *}
<div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
{* DESIGN: Control bar END *}</div></div></div></div></div></div>
</div></div>

<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h2 class="context-title">{'Unsubscribed member of groups'|i18n( 'design/nvnewsletter' )}</h2>

{* DESIGN: Mainline *}<div class="header-subline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content">

{* Group member table. *}
<table class="list" cellspacing="0">
<tr>
    <th class="tight">{'ID'|i18n('design/nvnewsletter')}</th>
    <th>{'Name'|i18n('design/nvnewsletter')}</th>
    <th>{'Description'|i18n( 'design/nvnewsletter' )}</th>
    <th>{'Unsubscribe date'|i18n( 'design/nvnewsletter' )}</th>
    <th>{'Unsubscribed by'|i18n( 'design/nvnewsletter' )}</th>
</tr>
{foreach $receiver.groups_unsubscribed as $group
         sequence array( bglight, bgdark ) as $seq}
<tr class="{$seq}">
    <td class="number">{$group.id}</td>
    <td><a href={concat( '/nvnewsletter/view_receiver_group/', $group.id, '/' )|ezurl}>{$group.group_name|wash}</a></td>
    <td>{$group.group_description|wash}</td>
    <td>{$group.unsub_date|makeunixtime()|l10n('shortdatetime')}</td>
    <td>
    {switch match=$group.status}
        {case match=11} 
        {'user'|i18n( 'design/nvnewsletter' )}
        {/case}
        {case match=12} 
        {'admin'|i18n( 'design/nvnewsletter' )}
        {/case}
        {case}
        {/case}
    {/switch}
    </td>
</tr>
{/foreach}
</table>

{* DESIGN: Content END *}</div></div></div>

{* Buttons. *}
<div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
{* DESIGN: Control bar END *}</div></div></div></div></div></div>
</div></div>
