{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* nvNewsletter - newsletter view *}

{def $senderFieldID=ezini('ContentClassSettings', 'SenderFieldIdentifier', 'nvnewsletter.ini')
     $groupFieldID=ezini('ContentClassSettings', 'GroupsFieldIdentifier', 'nvnewsletter.ini')}

<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h1 class="context-title">
    {'Newsletter <%newsletter_name>'|i18n('design/nvnewsletter',, hash('%newsletter_name', $newsletter.contentobject.name ) )|wash}
    {switch match=$newsletter.status}
        {case match=0}
            [{'Draft'|i18n('design/nvnewsletter')}]
        {/case}
    {/switch}
</h1>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content">

<div class="context-attributes">

    <div class="block float-break">

    {* Name *}
    <div class="block float-break">
        <label>{"Name"|i18n('design/nvnewsletter')}:</label> {$newsletter.contentobject.name|wash}
    </div>
    
    <br />

    {* Sender *}
    <div class="block float-break">
        {def $senderData=$newsletter.contentobject.data_map[$senderFieldID]}
        <label>{"Sender"|i18n('design/nvnewsletter')}:</label> <a href={concat( '/nvnewsletter/view_sender/', $senderData.content.selected, '/' )|ezurl}>{$senderData.content.options[$senderData.content.selected]}</a>
    </div>
    
    <br />

    {* Receiver groups *}
    <div class="block float-break">
        <label>{"Receiver groups"|i18n('design/nvnewsletter')}:</label>
        {def $groupData=$newsletter.contentobject.data_map[$groupFieldID]}
        {foreach $groupData.content.options as $key => $option}
            {if eq($groupData.content.selected.$key,'1')}
                <a href={concat( '/nvnewsletter/view_receiver_group/', $key, '/' )|ezurl}>{$option}</a><br />
            {/if}
        {/foreach}
    </div>
    
    <br />

    {if or($newsletter.status|eq(1), $newsletter.status|eq(2))}
    {* Send time *}
    <div class="block float-break">
        <label>{"Send time"|i18n('design/nvnewsletter')}:</label> {$newsletter.send_time|wash}
    </div>
    <br />
    {/if}

    {if $newsletter.status|eq(4)}
    {* Reason for failure *}
    <div class="block float-break">
        <label>{"Sending failed"|i18n('design/nvnewsletter')}:</label> {$newsletter.info|nl2br()}
    </div>
    <br />
    {/if}
    
    {* Preview *}
    <div class="block float-break">
        <label>{"Preview (not public)"|i18n('design/nvnewsletter')}:</label>
        {def $view_html_link = concat("nvnewsletter/preview/", $newsletter.contentobject_id, "/", $newsletter.contentobject_version, "/", $newsletter.locale)
             $view_text_link = concat( $view_html_link, '/text' )}
        <p>
            <a href={$view_html_link|ezurl} target="_blank">{'Show HTML formatted'|i18n('design/nvnewsletter')}</a><br />
            <a href={$$view_text_link|ezurl} target="_blank">{'Show text formatted'|i18n('design/nvnewsletter')}</a>
        </p>
    </div>

    <div class="break"></div>

</div>

{* DESIGN: Content END *}</div></div></div>
    {* Buttons. *}
    <div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
        <div class="block">
            {* Edit *}
            {if $newsletter.status|eq(0)}
                {def $currentLocale = ezini('RegionalSettings', 'Locale', 'site.ini')}
                <form name="edit_newsletter" method="post" action={'/content/action'|ezurl} style="display:inline">
                    <input type="hidden" name="RedirectURIAfterPublish" value="{concat('/nvnewsletter/view_newsletter/', $newsletter.id)}" />
                    <input type="hidden" name="RedirectIfDiscarded" value="{concat('/nvnewsletter/view_newsletter/', $newsletter.id)}" />
                    <input type="hidden" value="{$newsletter.contentobject.main_node_id}" name="ContentNodeID"/>
                    <input type="hidden" value="{$newsletter.contentobject.id}" name="ContentObjectID"/>
                    {if $currentLocale}
                    <input type="hidden" value="{$currentLocale}" name="ContentObjectLanguageCode" />
                    {/if}
                    <input class="button" type="submit" name="EditButton" value="{'Edit'|i18n('design/nvnewsletter')}" title="{'Edit this newsletter.'|i18n('design/nvnewsletter')}" />
                </form>
                <form name="queue_newsletter" method="post" action={concat('/nvnewsletter/queue_draft/', $newsletter.id)|ezurl} style="display:inline">
                    <input class="button" type="submit" value="{'Queue'|i18n('design/nvnewsletter')}" title="{'Queue newsletter.'|i18n('design/nvnewsletter')}" />
                </form>
            {/if}
        </div>
    </div>


{* DESIGN: Control bar END *}</div></div></div></div></div></div>
</div>
</div>

{include uri='design:nvnewsletter_children.tpl'}

<form name="send_preview" method="post" action={concat('/nvnewsletter/send_preview/', $newsletter.contentobject.id, '/', $newsletter.contentobject_version, '/', $newsletter.locale )|ezurl}>

<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h1 class="context-title">
    {'Send preview newsletter'|i18n('design/nvnewsletter',, hash('%newsletter_name', $newsletter.contentobject.name ) )|wash}
</h1>

{* DESIGN: Mainline *}<div class="header-subline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content">

<div class="context-attributes">

    <div class="block float-break">

        <div class="block float-break">
            <label for="PreviewEmail">{'Email address'|i18n('design/nvnewsletter')}:</label>
            <input type="text" name="PreviewEmail" id="previewEmail" value="" />
        </div>
        
        <div class="block float-break">
            <label>{'Format'|i18n('design/nvnewsletter')}:</label>
            <label class="checkbox"><input type="radio" name="PreviewFormat" checked="checked" value="1" /> HTML</label>
            <label class="checkbox"><input type="radio" name="PreviewFormat" value="0" /> Text</label>
        </div>
        
    </div>

    <div class="break"></div>

</div>

{* DESIGN: Content END *}</div></div></div>
    {* Buttons. *}
    <div class="controlbar" >
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
        <div class="block">
            <input type="hidden" value="{concat('/nvnewsletter/view_newsletter/', $newsletter.id)}" name="RedirectURIAfterPreview" />
            <input class="button" type="submit" value="{'Send preview'|i18n('design/nvnewsletter')}" title="{'Send preview newsletter'|i18n('design/nvnewsletter')}" />
        </div>
    </div>

{* DESIGN: Control bar END *}</div></div></div></div></div></div>
</div>
</div>

</form>

{if $newsletter.status|eq(3)}
<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h1 class="context-title">
    {'Statistics'|i18n('design/nvnewsletter')}
</h1>

{* DESIGN: Mainline *}<div class="header-subline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content">

<div class="context-attributes">

    <div class="block float-break">
    
        {def $newsletter_sent_mail_count = $newsletter.sent_mail_count}

        <div class="block float-break">
            <p><strong>{'Newsletters queued'|i18n('design/nvnewsletter')}:</strong>
            {$newsletter.total_mail_count}
            </p>
        </div>

        <div class="block float-break">
            <p><strong>{'Newsletters sent'|i18n('design/nvnewsletter')}:</strong>
            {$newsletter_sent_mail_count}
            </p>
        </div>
        
        <div class="block float-break">
            <p><strong>{'Newsletters opened (unique)'|i18n('design/nvnewsletter')}:</strong>
            {$newsletter.opened_count}
            ({'unique open rate'|i18n('design/nvnewsletter')}: {$newsletter.opened_count|div($newsletter_sent_mail_count)|mul(100)}%)
            </p>
        </div>
        
        <div class="block float-break">
            <p><strong>{'Newsletters opened (total)'|i18n('design/nvnewsletter')}:</strong>
            {$newsletter.opened_count_total}
            ({'total open rate'|i18n('design/nvnewsletter')}: {$newsletter.opened_count_total|div($newsletter_sent_mail_count)|mul(100)}%)
            </p>
        </div>

        <div class="block float-break">
            <p><strong>{'Unsubscribed'|i18n('design/nvnewsletter')}:</strong>
            {$newsletter.unsubscribe_count}
            ({'unsubscribe rate'|i18n('design/nvnewsletter')}: {$newsletter.unsubscribe_count|div($newsletter_sent_mail_count)|mul(100)}%)
            </p>
        </div>
        
        <div class="block float-break">
            <p><strong>{'Links clicked'|i18n('design/nvnewsletter')}:</strong>
            {$newsletter.link_click_count}
            ({'CTR'|i18n('design/nvnewsletter')}: 
            {if $newsletter.opened_count|gt(0)}
                {$newsletter.link_click_count|div($newsletter.opened_count)|mul(100)}%
            {else}
                0%
            {/if})
            </p>
        </div>
        
        <div class="block float-break">
            {def $links = $newsletter.links_clicked_by_date}
            {if $links}
                <table class="list" cellspacing="0">
                    <tbody>
                    <tr>
                        <th>{'Link clicks by date'|i18n('design/nvnewsletter')}</th>
                        <th>{'Click count'|i18n('design/nvnewsletter')}</th>
                    </tr>
                {foreach $links as $date => $link_array}
                    <tr class="bgdark">
                        <td colspan="2">{$date}</td>
                    </tr>
                   {if $link_array}
                      {foreach $link_array as $link}
                    <tr class="bglight">
                        <td><a href="{$link.link|wash}" target="_blank">{$link.link|wash}</a></td>
                        <td>{$link.data_int}</td>
                    </tr>
                      {/foreach}
                   {/if}
                {/foreach}
                    </tbody>
                </table>
            {/if}
        </div>
        
        <div class="block float-break">
            {set $links = $newsletter.links_clicked}
            {if $links}
                <table class="list" cellspacing="0">
                    <tbody>
                    <tr>
                        <th>{'Total clicks'|i18n('design/nvnewsletter')}</th>
                        <th>{'Click count'|i18n('design/nvnewsletter')}</th>
                    </tr>
                {foreach $links as $link}
                    <tr class="bglight">
                        <td><a href="{$link.link|wash}" target="_blank">{$link.link|wash}</a></td>
                        <td>{$link.count}</td>
                    </tr>
                {/foreach}
                    </tbody>
                </table>
            {/if}
        </div>
    </div>

    <div class="break"></div>

</div>

{* DESIGN: Content END *}</div></div></div>
    {* Buttons. *}
    <div class="controlbar" >
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
        <div class="block">
        </div>
    </div>

{* DESIGN: Control bar END *}</div></div></div></div></div></div>
</div>
</div>
{/if}