{* DO NOT EDIT THIS FILE! Use an override template instead. *}

{def $newsletter_draft_count=fetch( 'nvnewsletter', 'drafts_newsletter_count' )
     $newsletter_sent_count=fetch( 'nvnewsletter', 'sent_newsletter_count' )
     $newsletter_failed_count=fetch( 'nvnewsletter', 'failed_newsletter_count' )
     $newsletter_in_progress_count=fetch( 'nvnewsletter', 'in_progress_newsletter_count' )
     $newsletter_groups_count=fetch( 'nvnewsletter', 'receiver_group_count' )
     $newsletter_receivers_count=fetch( 'nvnewsletter', 'receiver_count' )
     $newsletter_unsubscribed_count=fetch( 'nvnewsletter', 'unsubscribed_count' )
     $sender_field_id=ezini( 'ContentClassSettings', 'SenderFieldIdentifier', 'nvnewsletter.ini' )
     $group_field_id=ezini( 'ContentClassSettings', 'GroupsFieldIdentifier', 'nvnewsletter.ini' )
     $page_limit = $limit}

<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h1 class="context-title">{'Newsletter dashboard'|i18n( 'design/nvnewsletter' )}</h1>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content overflow">

<table class="list" cellspacing="0">
<tr>
    <th>{'Sent'|i18n( 'design/nvnewsletter' )}</th>
    <th>{'In progress'|i18n( 'design/nvnewsletter' )}</th>
    <th>{'Drafts'|i18n( 'design/nvnewsletter' )}</th>
    <th>{'Failed'|i18n( 'design/nvnewsletter' )}</th>
    <th>{'Groups'|i18n( 'design/nvnewsletter' )}</th>
    <th>{'Receivers'|i18n( 'design/nvnewsletter' )}</th>
    <th>{'Unsubscribed'|i18n( 'design/nvnewsletter' )}</th>
</tr>
<tr class="bglight">
    <td>{$newsletter_sent_count}</td>
    <td>{$newsletter_in_progress_count}</td>
    <td>{$newsletter_draft_count}</td>
    <td>{$newsletter_failed_count}</td>
    <td>{$newsletter_groups_count}</td>
    <td>{$newsletter_receivers_count}</td>
    <td>{$newsletter_unsubscribed_count}</td>
</tr>
</table>

{* DESIGN: Content END *}</div></div></div>

{* Buttons. *}
<div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
<div class="block">
</div>
{* DESIGN: Control bar END *}</div></div></div></div></div></div>
</div>
</div>

<form name="newsletters" method="post" action={'/nvnewsletter/list_draft/'|ezurl}>
<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h1 class="context-title">{'Latest drafts'|i18n( 'design/nvnewsletter' )}</h1>

{* DESIGN: Mainline *}<div class="header-subline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content overflow">

{* Items per page selector. *}
<div class="context-toolbar">
<div class="block">
<div class="left">
</div>
<div class="break"></div>
</div>
</div>

{* Drafts newsletters table. *}
<table class="list" cellspacing="0">
<tr>
    <th class="tight"><img src={'toggle-button-16x16.gif'|ezimage} alt="{'Invert selection'|i18n('design/nvnewsletter')}" title="{'Invert selection.'|i18n('design/nvnewsletter')}" onclick="ezjs_toggleCheckboxes( document.newsletters, 'NewsletterIDArray[]' ); return false;" /></th>
    <th class="tight">{'ID'|i18n( 'design/nvnewsletter' )}</th>
    <th>{'Name'|i18n( 'design/nvnewsletter' )}</th>
    <th>{'Sender'|i18n( 'design/nvnewsletter' )}</th>
    <th>{'Receiver groups'|i18n( 'design/nvnewsletter' )}</th>
    <th>{'Created time'|i18n( 'design/nvnewsletter' )}</th>
    <!--th class="tight">&nbsp;</th-->
</tr>
{if $newsletter_draft_count|lt(1)}
<tr><td>&nbsp;</td><td colspan="4">{'No newsletter drafts'|i18n( 'design/nvnewsletter' )}</td><td>&nbsp;</td></tr>
{else}
{foreach $newsletter_draft_array as $newsletter
         sequence array( bglight, bgdark ) as $seq}
<tr class="{$seq}">
    <td><input type="checkbox" name="NewsletterIDArray[]" value="{$newsletter.id}" title="{'Select newsletter for removal.'|i18n( 'design/nvnewsletter' )}" /></td>
    <td class="number" align="right">{$newsletter.id}</td>
    <td>{'newsletter'|icon( 'small', 'Newsletter'|i18n( 'design/nvnewsletter' ) )}&nbsp;<a href={concat( '/nvnewsletter/view_newsletter/', $newsletter.id, '/' )|ezurl}>{$newsletter.contentobject.name|wash}</a></td>
    {def $sender_data=$newsletter.contentobject.data_map[$sender_field_id]}
    <td><a href={concat( '/nvnewsletter/view_sender/', $sender_data.content.selected, '/' )|ezurl}>{$sender_data.content.options[$sender_data.content.selected]}</a></td>
    <td>
        {def $group_data=$newsletter.contentobject.data_map[$group_field_id]}
        {foreach $group_data.content.options as $key => $option}
            {if eq($group_data.content.selected.$key,'1')}
                <a href={concat( '/nvnewsletter/view_receiver_group/', $key, '/' )|ezurl}>{$option}</a><br />
            {/if}
        {/foreach}
    </td>
    <td>{$newsletter.contentobject.published|l10n('shortdatetime')}</td>
</tr>
{undef $sender_data $group_data}
{/foreach}
{/if}
</table>

{* DESIGN: Content END *}</div></div></div>

{* Buttons. *}
<div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
<div class="block">
<input class="button" type="submit" name="RemoveNewsletterButton" value="{'Remove selected'|i18n( 'design/nvnewsletter' )}" title="{'Remove selected newsletters.'|i18n( 'design/nvnewsletter' )}" />
<input class="button" type="submit" name="CreateNewsletterButton" value="{'New newsletter'|i18n( 'design/nvnewsletter' )}" title="{'Create a new newsletter.'|i18n( 'design/nvnewsletter' )}" />
</div>
{* DESIGN: Control bar END *}</div></div></div></div></div></div>
</div>
</div>
</form>