{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* nvNewsletter - edit sender *}
<form method="post" action={concat('/nvnewsletter/edit_sender/', $sender.id, '/')|ezurl}>

{if $warning|count}
    <div class="message-warning">
    <h2>{'The validation of your entries failed.'|i18n('design/nvnewsletter' )}</h2>
    <ul>
    {foreach $warning as $warningmessage}
        <li>{$warningmessage|wash}</li>
    {/foreach}
    </ul>
    </div>
{/if}


<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h1 class="context-title">{'Edit sender'|i18n( 'design/nvnewsletter' )}</h1>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content">

<input type="hidden" name="SenderID" value ="{$sender.id}"/>

<div class="context-attributes">

{* Name. *}
<div class="block">
<label for="name">{'Name'|i18n( 'design/nvnewsletter' )}:</label>
<input id="name" class="box" id="senderName" type="text" name="SenderName" value="{$sender.sender_name|wash}" />
</div>

{* E-mail. *}
<div class="block">
<label for="sender">{'Sender address'|i18n( 'design/nvnewsletter' )}:</label>
<input id="sender" class="box" id="senderAddress" type="text" name="SenderAddress" value="{$sender.sender_email|wash}" />
</div>

{* Reply-to. *}
<div class="block">
<label for="replyto">{'Reply-to address'|i18n( 'design/nvnewsletter' )}:</label>
<input id="replyto" class="box" id="replyToAddress" type="text" name="ReplyToAddress" value="{$sender.reply_to|wash}" />
</div>

</div>

{* DESIGN: Content END *}</div></div></div>

<div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
<div class="block">
<input class="button" type="submit" name="StoreButton" value="{'OK'|i18n( 'design/nvnewsletter' )}" />
<input class="button" type="submit" name="CancelButton" value="{'Cancel'|i18n( 'design/nvnewsletter' )}" />
</div>
{* DESIGN: Control bar END *}</div></div></div></div></div></div>
</div>

</div>
</form>


{literal}
<script language="JavaScript" type="text/javascript">
<!--
    window.onload=function() {
        document.getElementById('senderName').select();
        document.getElementById('senderName').focus();
    }
-->
</script>
{/literal}
