{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* nvNewsletter - receiver search *}
{def $page_limit = $limit
     $searchText = ezhttp('SearchText', 'get')}

{include uri='design:parts/search_receivers_form.tpl'}

<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h1 class="context-title">{'Receiver search results'|i18n( 'design/nvnewsletter' )} [{$receiver_count}]</h1>

{* DESIGN: Mainline *}<div class="header-subline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content overflow">

{* Items per page selector. *}
<div class="context-toolbar">
<div class="button-left">
    <p class="table-preferences">
        {switch match=$page_limit}
        {case match=25}
        <a href={'/user/preferences/set/admin_list_limit/1'|ezurl} title="{'Show 10 items per page.'|i18n( 'design/admin/node/view/full' )}">10</a>
        <span class="current">25</span>
        <a href={'/user/preferences/set/admin_list_limit/3'|ezurl} title="{'Show 50 items per page.'|i18n( 'design/admin/node/view/full' )}">50</a>
        {/case}

        {case match=50}
        <a href={'/user/preferences/set/admin_list_limit/1'|ezurl} title="{'Show 10 items per page.'|i18n( 'design/admin/node/view/full' )}">10</a>
        <a href={'/user/preferences/set/admin_list_limit/2'|ezurl} title="{'Show 25 items per page.'|i18n( 'design/admin/node/view/full' )}">25</a>
        <span class="current">50</span>
        {/case}

        {case}
        <span class="current">10</span>
        <a href={'/user/preferences/set/admin_list_limit/2'|ezurl} title="{'Show 25 items per page.'|i18n( 'design/admin/node/view/full' )}">25</a>
        <a href={'/user/preferences/set/admin_list_limit/3'|ezurl} title="{'Show 50 items per page.'|i18n( 'design/admin/node/view/full' )}">50</a>
        {/case}
        {/switch}
    </p>
</div>
<div class="float-break"></div>
</div>

{* Newsletter receiver table. *}
<table class="list" cellspacing="0">
{if $receiver_count|lt(1)}
    {if $searchText|eq('')}
    <tr><td>{'No search word.'|i18n( 'design/nvnewsletter' )}</td></tr>
    {else}
    <tr><td>{'No receivers found.'|i18n( 'design/nvnewsletter' )}</td></tr>
    {/if}
{else}
<tr>
    <th>{'Email'|i18n( 'design/nvnewsletter' )}</th>
    <th class="tight">{'ID'|i18n( 'design/nvnewsletter' )}</th>
    <th class="tight">&nbsp;</th>
</tr>
{foreach $receiver_array as $receiver
         sequence array( bglight, bgdark ) as $seq}
<tr class="{$seq}">
    <td>{'newsletter'|icon( 'small', 'Newsletter'|i18n( 'design/nvnewsletter' ) )}&nbsp;<a href={concat( '/nvnewsletter/view_receiver/', $receiver.id, '/' )|ezurl}>{$receiver.email_address|wash}</a></td>
    <td class="number" align="right">{$receiver.id}</td>
    <td><a href={concat( '/nvnewsletter/edit_receiver/', $receiver.id, '/' )|ezurl}><img src={'edit.gif'|ezimage} alt="{'Edit'|i18n( 'design/nvnewsletter' )}" title="{'Edit the <%receiver_email> receiver.'|i18n( 'design/nvnewsletter',, hash( '%receiver_email', $receiver.email_address ) )|wash}" /></a></td>
</tr>
{/foreach}
{/if}
</table>

{* Navigator. *}
<div class="context-toolbar">
{include name=navigator
         uri='design:navigator/google.tpl'
         page_uri='/nvnewsletter/search_receivers'
         page_uri_suffix=concat('?SearchText=', $searchText|urlencode, '&SearchFrom=', $search_from )
         item_count=$receiver_count
         view_parameters=$view_parameters
         item_limit=$page_limit}
</div>

{* DESIGN: Content END *}</div></div></div>

{* Buttons. *}
<div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
<div class="block">
<form name="receivers" method="post" action={'/nvnewsletter/edit_receiver/'|ezurl}>
<input class="button" type="submit" name="CreateReceiverButton" value="{'New receiver'|i18n( 'design/nvnewsletter' )}" title="{'Create a new receiver.'|i18n( 'design/nvnewsletter' )}" />
</form>
</div>
{* DESIGN: Control bar END *}</div></div></div></div></div></div>
</div>
</div>