{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* nvNewsletter - receiver field view *}

{def $base_uri=concat('/nvnewsletter/view_receiver_field/', $field.id)}

<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h1 class="context-title">{'Receiver field <%field_name>'|i18n('design/nvnewsletter',, hash('%field_name', $field.field_name ) )|wash}</h1>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content">

<div class="context-attributes">

    <div class="block float-break">

    {* Name *}
    <div class="block float-break">
        <label>{"Name"|i18n('design/nvnewsletter')}:</label> {$field.field_name|wash}
    </div>

    {* Type *}
    <div class="block float-break">
        <label>{"Type"|i18n('design/nvnewsletter')}:</label> {$field.field_type|wash}
    </div>

    {* Required *}
    <div class="block float-break">
        <label>{"Required"|i18n('design/nvnewsletter')}:</label> {if $field.required}X{/if}
    </div>

    {* Meta *}
    <div class="block float-break">
        <label>{"Metadata"|i18n('design/nvnewsletter')}:</label> {$field.meta}
    </div>

    <div class="break"></div>

</div>

{* DESIGN: Content END *}</div></div></div>
    {* Buttons. *}
    <div class="controlbar" >
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
        {* Edit *}
        <div class="left">
        <form name="edit_receiver_field" method="post" action={concat('/nvnewsletter/edit_receiver_field/', $field.id)|ezurl} style="display:inline">
        <input class="button" type="submit" value="{'Edit'|i18n('design/nvnewsletter')}" title="{'Edit this receiver field.'|i18n('design/nvnewsletter')}" />
        </form>
        </div>
    </div>


{* DESIGN: Control bar END *}</div></div></div></div></div></div>
</div>
</div>
